use std::fmt::{Arguments, Write as _};

use crate::error::{DiaggenError, DiaggenResult};
use crate::model::{Catalog, Entry, KindMap, MapMode, MapTarget};

pub fn render_catalog(catalog: &Catalog) -> DiaggenResult<String> {
    let enum_name = catalog
        .enum_name
        .as_ref()
        .ok_or_else(|| DiaggenError(format!("catalog `{}` missing enum name", catalog.owner)))?;
    let mut out = String::new();
    out.push_str(
        r"// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use music_base::diag::DiagContext;
",
    );
    push_fmt(&mut out, format_args!("use super::{enum_name};\n\n"));
    render_entry_struct(&mut out, enum_name);
    render_entries(&mut out, enum_name, &catalog.entries);
    render_accessors(&mut out, enum_name);
    for map in &catalog.maps {
        out.push('\n');
        render_map(&mut out, enum_name, map);
    }
    Ok(out)
}

fn render_entry_struct(out: &mut String, enum_name: &str) {
    out.push_str("struct CatalogEntry {\n");
    push_fmt(out, format_args!("    kind: {enum_name},\n"));
    out.push_str("    code: u16,\n");
    out.push_str("    message: &'static str,\n");
    out.push_str("    primary: &'static str,\n");
    out.push_str("    secondary: Option<&'static str>,\n");
    out.push_str("    help: Option<&'static str>,\n");
    out.push_str("}\n\n");
}

fn render_entries(out: &mut String, enum_name: &str, entries: &[Entry]) {
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("const ENTRIES: &[CatalogEntry] = &[\n");
    for entry in entries {
        out.push_str("    CatalogEntry {\n");
        push_fmt(
            out,
            format_args!("        kind: {enum_name}::{},\n", entry.kind),
        );
        push_fmt(out, format_args!("        code: {},\n", entry.code));
        push_fmt(
            out,
            format_args!("        message: \"{}\",\n", rust_string(&entry.message)),
        );
        push_fmt(
            out,
            format_args!("        primary: \"{}\",\n", rust_string(&entry.primary)),
        );
        match &entry.secondary {
            Some(secondary) => push_fmt(
                out,
                format_args!("        secondary: Some(\"{}\"),\n", rust_string(secondary)),
            ),
            None => out.push_str("        secondary: None,\n"),
        }
        match &entry.help {
            Some(help) => push_fmt(
                out,
                format_args!("        help: Some(\"{}\"),\n", rust_string(help)),
            ),
            None => out.push_str("        help: None,\n"),
        }
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");
}

fn render_accessors(out: &mut String, enum_name: &str) {
    push_fmt(
        out,
        format_args!(
            "fn entry(kind: {enum_name}) -> &'static CatalogEntry {{\n    ENTRIES\n        .iter()\n        .find(|entry| entry.kind == kind)\n        .expect(\"missing generated diagnostic catalog entry\")\n}}\n\n"
        ),
    );
    push_fmt(
        out,
        format_args!("pub fn code(kind: {enum_name}) -> u16 {{\n    entry(kind).code\n}}\n\n"),
    );
    push_fmt(
        out,
        format_args!(
            "pub fn message(kind: {enum_name}) -> &'static str {{\n    entry(kind).message\n}}\n\n"
        ),
    );
    push_fmt(
        out,
        format_args!(
            "pub fn primary(kind: {enum_name}) -> &'static str {{\n    entry(kind).primary\n}}\n\n"
        ),
    );
    push_fmt(
        out,
        format_args!(
            "pub fn render_message(kind: {enum_name}, context: &DiagContext) -> String {{\n    context.render(entry(kind).message)\n}}\n\n"
        ),
    );
    push_fmt(
        out,
        format_args!(
            "pub fn render_primary(kind: {enum_name}, context: &DiagContext) -> String {{\n    context.render(entry(kind).primary)\n}}\n\n"
        ),
    );
    push_fmt(
        out,
        format_args!(
            "pub fn secondary(kind: {enum_name}) -> Option<&'static str> {{\n    entry(kind).secondary\n}}\n\n"
        ),
    );
    push_fmt(
        out,
        format_args!(
            "pub fn render_secondary(kind: {enum_name}, context: &DiagContext) -> Option<String> {{\n    entry(kind).secondary.map(|secondary| context.render(secondary))\n}}\n\n"
        ),
    );
    push_fmt(
        out,
        format_args!(
            "pub fn help(kind: {enum_name}) -> Option<&'static str> {{\n    entry(kind).help\n}}\n\n"
        ),
    );
    push_fmt(
        out,
        format_args!(
            "pub fn from_code(raw: u16) -> Option<{enum_name}> {{\n    ENTRIES\n        .iter()\n        .find(|entry| entry.code == raw)\n        .map(|entry| entry.kind)\n}}\n"
        ),
    );
}

fn render_map(out: &mut String, enum_name: &str, map: &KindMap) {
    out.push_str("#[rustfmt::skip]\n");
    let return_type = match map.mode {
        MapMode::Required => enum_name.to_owned(),
        MapMode::Option => format!("Option<{enum_name}>"),
    };
    let source_ref = if map.source_by_value { "" } else { "&" };
    let signature = format!(
        "pub const fn {}(source: {source_ref}{}) -> {return_type}",
        map.name, map.source_type
    );
    if signature.len() >= 100 {
        push_fmt(
            out,
            format_args!(
                "pub const fn {}(\n    source: {source_ref}{},\n) -> {return_type} {{\n    match source {{\n",
                map.name, map.source_type
            ),
        );
    } else {
        push_fmt(out, format_args!("{signature} {{\n    match source {{\n"));
    }
    let mut index = 0;
    while index < map.cases.len() {
        let start = index;
        let target = &map.cases[start].target;
        index += 1;
        while index < map.cases.len() && map.cases[index].target == *target {
            index += 1;
        }
        render_map_arm(out, enum_name, map, start, index);
    }
    out.push_str("    }\n}\n");
}

fn render_map_arm(out: &mut String, enum_name: &str, map: &KindMap, start: usize, end: usize) {
    let mut patterns = String::new();
    for (offset, case) in map.cases[start..end].iter().enumerate() {
        if offset > 0 {
            patterns.push_str("\n        | ");
        }
        push_fmt(
            &mut patterns,
            format_args!("{}::{}", map.source_type, case.pattern),
        );
    }
    let target = rendered_map_target(enum_name, map.mode, &map.cases[start].target);
    let pattern_len = patterns.lines().map(str::len).max().unwrap_or_default();
    let inline_len = pattern_len
        .saturating_add("        ".len())
        .saturating_add(" => ".len())
        .saturating_add(target.len())
        .saturating_add(",".len());
    if inline_len > 100 {
        push_fmt(
            out,
            format_args!("        {patterns} => {{\n            {target}\n        }}\n"),
        );
    } else {
        push_fmt(out, format_args!("        {patterns} => {target},\n"));
    }
}

fn rendered_map_target(enum_name: &str, mode: MapMode, target: &MapTarget) -> String {
    match (mode, target) {
        (MapMode::Option, MapTarget::None) => "None".to_owned(),
        (MapMode::Option, MapTarget::Kind(kind)) => format!("Some({enum_name}::{kind})"),
        (MapMode::Required, MapTarget::Kind(kind)) => format!("{enum_name}::{kind}"),
        (MapMode::Required, MapTarget::None) => {
            "compile_error!(\"invalid required diagnostic map target\")".to_owned()
        }
    }
}

fn push_fmt(out: &mut String, args: Arguments<'_>) {
    out.write_fmt(args)
        .expect("write generated diagnostics text");
}

fn rust_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests;
