// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use music_base::diag::DiagContext;
use super::SeamDiagKind;

struct CatalogEntry {
    kind: SeamDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    secondary: Option<&'static str>,
    help: Option<&'static str>,
}

#[rustfmt::skip]
const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: SeamDiagKind::ArtifactValidationFailed,
        code: 5400,
        message: "artifact validation failed (`{source}`)",
        primary: "artifact validation failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::InvalidBinaryHeader,
        code: 5401,
        message: "`SEAM` binary header invalid",
        primary: "`SEAM` binary header invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::UnsupportedBinaryVersion,
        code: 5402,
        message: "binary version `{version}` unsupported",
        primary: "binary version `{version}` unsupported",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::UnknownSectionTag,
        code: 5403,
        message: "section tag `{tag}` unknown",
        primary: "section tag `{tag}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::BinaryPayloadTruncated,
        code: 5404,
        message: "binary payload truncated",
        primary: "binary payload truncated",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::UnknownOpcode,
        code: 5405,
        message: "opcode `{opcode}` unknown",
        primary: "opcode `{opcode}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextParseFailed,
        code: 5406,
        message: "text parse failed (`{source}`)",
        primary: "text parse failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::InvalidReference,
        code: 5407,
        message: "table reference `{table}` invalid",
        primary: "table reference `{table}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::DuplicateLabel,
        code: 5408,
        message: "procedure `{procedure}` label duplicate",
        primary: "procedure `{procedure}` label duplicate",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::MissingLabel,
        code: 5409,
        message: "procedure `{procedure}` label reference missing",
        primary: "procedure `{procedure}` label reference missing",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::InvalidEffectOp,
        code: 5410,
        message: "effect operation reference `effect.op` invalid",
        primary: "effect operation reference `effect.op` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::OperandShapeMismatch,
        code: 5411,
        message: "opcode `{opcode}` operand shape mismatch",
        primary: "opcode `{opcode}` operand shape mismatch",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilMissingEntryBlock,
        code: 5412,
        message: "HIL function `{function}` missing entry block",
        primary: "HIL function `{function}` missing entry block",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilDuplicateBlock,
        code: 5413,
        message: "HIL function `{function}` block `{block}` duplicate",
        primary: "HIL block `{block}` duplicate",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilDuplicateValue,
        code: 5414,
        message: "HIL value `{value}` defined more than once",
        primary: "HIL value `{value}` duplicate",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilUndefinedValue,
        code: 5415,
        message: "HIL value `{value}` used before definition",
        primary: "HIL value `{value}` undefined",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilTypeMismatch,
        code: 5416,
        message: "HIL value `{value}` expected `{expected}`, found `{found}`",
        primary: "HIL value `{value}` type mismatch",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilMissingBlockTarget,
        code: 5417,
        message: "HIL branch target `{target}` missing",
        primary: "HIL branch target `{target}` missing",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilReturnTypeMismatch,
        code: 5418,
        message: "HIL return expected `{expected}`, found `{found}`",
        primary: "HIL return type mismatch",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilReturnValueMissing,
        code: 5419,
        message: "HIL return value for result `{expected}` missing",
        primary: "HIL return value for result `{expected}` missing",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilReturnValueUnexpected,
        code: 5420,
        message: "HIL return value unexpected for unit result `()`",
        primary: "HIL return value unexpected for unit result `()`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilShapeRequired,
        code: 5421,
        message: "HIL shape `{shape}` required",
        primary: "HIL shape `{shape}` required",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextExpectedForm,
        code: 5422,
        message: "SEAM text form expected `{form}`",
        primary: "form `{form}` expected",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextMissingOperand,
        code: 5423,
        message: "SEAM text operand `{operand}` missing",
        primary: "operand `{operand}` missing",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextInvalidOperand,
        code: 5424,
        message: "SEAM text operand `{operand}` value `{value}` invalid",
        primary: "operand `{operand}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextUnknownDirective,
        code: 5425,
        message: "SEAM directive `{directive}` unknown",
        primary: "directive `{directive}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextUnknownOpcode,
        code: 5426,
        message: "SEAM opcode `{opcode}` unknown",
        primary: "opcode `{opcode}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextUnknownSymbol,
        code: 5427,
        message: "SEAM `{kind}` symbol `{symbol}` unknown",
        primary: "`{kind}` symbol `{symbol}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextDuplicateSymbol,
        code: 5428,
        message: "SEAM `{kind}` symbol `{symbol}` duplicate",
        primary: "`{kind}` symbol `{symbol}` duplicate",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextUnterminatedString,
        code: 5429,
        message: "unterminated SEAM string literal `{literal}`",
        primary: "unterminated string literal",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextUnexpectedEnd,
        code: 5430,
        message: "`.end` unexpected outside procedure",
        primary: "`.end` unexpected here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextUnterminatedProcedure,
        code: 5431,
        message: "unterminated procedure block `{procedure}`",
        primary: "procedure `{procedure}` missing `.end`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextCountMismatch,
        code: 5432,
        message: "SEAM `{kind}` count expected `{expected}`, found `{found}`",
        primary: "`{kind}` count mismatch",
        secondary: None,
        help: None,
    },
];

fn entry(kind: SeamDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: SeamDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: SeamDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: SeamDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn render_message(kind: SeamDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).message)
}

pub fn render_primary(kind: SeamDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).primary)
}

pub fn secondary(kind: SeamDiagKind) -> Option<&'static str> {
    entry(kind).secondary
}

pub fn render_secondary(kind: SeamDiagKind, context: &DiagContext) -> Option<String> {
    entry(kind).secondary.map(|secondary| context.render(secondary))
}

pub fn help(kind: SeamDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<SeamDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

#[rustfmt::skip]
pub const fn assembly_error_kind(source: &crate::AssemblyError) -> SeamDiagKind {
    match source {
        crate::AssemblyError::ArtifactValidationFailed(_) => SeamDiagKind::ArtifactValidationFailed,
        crate::AssemblyError::InvalidBinaryHeader => SeamDiagKind::InvalidBinaryHeader,
        crate::AssemblyError::UnsupportedBinaryVersion(_) => SeamDiagKind::UnsupportedBinaryVersion,
        crate::AssemblyError::UnknownSectionTag(_) => SeamDiagKind::UnknownSectionTag,
        crate::AssemblyError::BinaryPayloadTruncated => SeamDiagKind::BinaryPayloadTruncated,
        crate::AssemblyError::UnknownOpcode(_) => SeamDiagKind::UnknownOpcode,
        crate::AssemblyError::TextParseFailed(_) => SeamDiagKind::TextParseFailed,
    }
}

#[rustfmt::skip]
pub const fn artifact_error_kind(source: &crate::ArtifactError) -> SeamDiagKind {
    match source {
        crate::ArtifactError::InvalidReference { .. } => SeamDiagKind::InvalidReference,
        crate::ArtifactError::DuplicateLabel { .. } => SeamDiagKind::DuplicateLabel,
        crate::ArtifactError::MissingLabel { .. } => SeamDiagKind::MissingLabel,
        crate::ArtifactError::InvalidEffectOp => SeamDiagKind::InvalidEffectOp,
        crate::ArtifactError::OperandShapeMismatch { .. } => SeamDiagKind::OperandShapeMismatch,
    }
}

#[rustfmt::skip]
pub const fn hil_verify_error_kind(source: &crate::HilVerifyError) -> SeamDiagKind {
    match source {
        crate::HilVerifyError::MissingEntryBlock { .. } => SeamDiagKind::HilMissingEntryBlock,
        crate::HilVerifyError::DuplicateBlock { .. } => SeamDiagKind::HilDuplicateBlock,
        crate::HilVerifyError::DuplicateValue { .. } => SeamDiagKind::HilDuplicateValue,
        crate::HilVerifyError::UndefinedValue { .. } => SeamDiagKind::HilUndefinedValue,
        crate::HilVerifyError::TypeMismatch { .. } => SeamDiagKind::HilTypeMismatch,
        crate::HilVerifyError::MissingBlockTarget { .. } => SeamDiagKind::HilMissingBlockTarget,
        crate::HilVerifyError::ReturnTypeMismatch { .. } => SeamDiagKind::HilReturnTypeMismatch,
        crate::HilVerifyError::ReturnValueMissing { .. } => SeamDiagKind::HilReturnValueMissing,
        crate::HilVerifyError::ReturnValueUnexpected => SeamDiagKind::HilReturnValueUnexpected,
        crate::HilVerifyError::ShapeRequired { .. } => SeamDiagKind::HilShapeRequired,
    }
}
