// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use music_base::diag::DiagContext;
use super::SyntaxDiagKind;

struct CatalogEntry {
    kind: SyntaxDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    secondary: Option<&'static str>,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: SyntaxDiagKind::InvalidChar,
        code: 1200,
        message: "character `{ch}` invalid",
        primary: "character `{ch}` not valid here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::UnterminatedStringLiteral,
        code: 1201,
        message: "missing closing `\"` in string literal",
        primary: "string starts here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::UnterminatedRuneLiteral,
        code: 1202,
        message: "missing closing `'` in rune literal",
        primary: "rune starts here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::EmptyRuneLiteral,
        code: 1203,
        message: "rune literal needs unicode scalar",
        primary: "rune literal needs unicode scalar",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::RuneLiteralTooLong,
        code: 1204,
        message: "rune literal contains multiple unicode scalars",
        primary: "rune literal payload too long",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::UnterminatedBlockComment,
        code: 1205,
        message: "missing closing `-/` in block comment",
        primary: "comment starts here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::UnterminatedTemplateLiteral,
        code: 1206,
        message: "missing closing ``` in template literal",
        primary: "template starts here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::MissingDigitsAfterBasePrefix,
        code: 1207,
        message: "missing digits after base `{base}` prefix",
        primary: "base `{base}` prefix needs digits",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::InvalidDigitForBase,
        code: 1208,
        message: "digit `{ch}` invalid in base `{base}` literal",
        primary: "digit `{ch}` not valid for base `{base}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::UnexpectedUnderscoreInNumberLiteral,
        code: 1209,
        message: "number literal `_` unexpected",
        primary: "underscore cannot appear here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::MissingDigitAfterUnderscoreInNumberLiteral,
        code: 1210,
        message: "missing digit after `_` in number literal",
        primary: "missing digit after `_`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::MissingExponentDigits,
        code: 1211,
        message: "missing exponent digits",
        primary: "exponent marker needs digits",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::MissingEscapeCode,
        code: 1212,
        message: "missing escape code",
        primary: "missing escape code after `\\`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::UnexpectedEscape,
        code: 1213,
        message: "unexpected escape `\\{ch}`",
        primary: "unexpected escape `\\{ch}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::MissingHexDigitsInByteEscape,
        code: 1214,
        message: "missing hex digits in `\\x` escape",
        primary: "missing hex digits after `\\x`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::InvalidHexDigitInByteEscape,
        code: 1215,
        message: "invalid hex digit `{ch}` in `\\x` escape",
        primary: "hex digit `{ch}` not valid here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::MissingHexDigitsInUnicodeEscape,
        code: 1216,
        message: "missing hex digits in `\\u` escape",
        primary: "missing hex digits after `\\u`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::InvalidHexDigitInUnicodeEscape,
        code: 1217,
        message: "invalid hex digit `{ch}` in `\\u` escape",
        primary: "hex digit `{ch}` not valid here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedFourOrSixHexDigitsInUnicodeEscape,
        code: 1218,
        message: "`\\u` escape needs 4 or 6 hex digits",
        primary: "`\\u` escape length must be 4 or 6 hex digits",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::InvalidUnicodeScalar,
        code: 1219,
        message: "unicode scalar `U+{value}` invalid",
        primary: "unicode scalar `U+{value}` not valid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedToken,
        code: 1300,
        message: "token expected {expected}, found {found}",
        primary: "found {found} here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedExpression,
        code: 1301,
        message: "expression expected, found {found}",
        primary: "found {found} here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedPattern,
        code: 1302,
        message: "pattern expected, found {found}",
        primary: "found {found} here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedMember,
        code: 1303,
        message: "member expected, found {found}",
        primary: "found {found} here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedIdentifier,
        code: 1304,
        message: "identifier expected, found {found}",
        primary: "found {found} here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedSpliceTarget,
        code: 1305,
        message: "splice target expected, found {found}",
        primary: "found {found} here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedOperatorMemberName,
        code: 1306,
        message: "operator member name expected, found {found}",
        primary: "found {found} here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedFieldTarget,
        code: 1307,
        message: "field name or tuple index expected, found {found}",
        primary: "found {found} here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedConstraintOperator,
        code: 1308,
        message: "constraint operator `<:` or `:` expected, found {found}",
        primary: "found {found} here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedAttrValue,
        code: 1309,
        message: "attribute value expected, found {found}",
        primary: "found {found} here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::SpliceOutsideQuote,
        code: 1310,
        message: "splice only valid inside quote",
        primary: "splice appears outside quote",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::NonAssociativeChain,
        code: 1311,
        message: "comparison chain needs grouping",
        primary: "chain continues here",
        secondary: None,
        help: Some("parenthesize comparison"),
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ReservedKeywordIdentifier,
        code: 1312,
        message: "reserved keyword {keyword} cannot name identifier",
        primary: "{keyword} found where identifier required",
        secondary: None,
        help: Some("choose non-keyword identifier"),
    },
];

fn entry(kind: SyntaxDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: SyntaxDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: SyntaxDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: SyntaxDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn render_message(kind: SyntaxDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).message)
}

pub fn render_primary(kind: SyntaxDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).primary)
}

pub fn secondary(kind: SyntaxDiagKind) -> Option<&'static str> {
    entry(kind).secondary
}

pub fn render_secondary(kind: SyntaxDiagKind, context: &DiagContext) -> Option<String> {
    entry(kind).secondary.map(|secondary| context.render(secondary))
}

pub fn help(kind: SyntaxDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<SyntaxDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn lex_error_kind(source: super::LexErrorKind) -> SyntaxDiagKind {
    match source {
        super::LexErrorKind::InvalidChar { .. } => SyntaxDiagKind::InvalidChar,
        super::LexErrorKind::UnterminatedStringLiteral => SyntaxDiagKind::UnterminatedStringLiteral,
        super::LexErrorKind::UnterminatedRuneLiteral => SyntaxDiagKind::UnterminatedRuneLiteral,
        super::LexErrorKind::EmptyRuneLiteral => SyntaxDiagKind::EmptyRuneLiteral,
        super::LexErrorKind::RuneLiteralTooLong => SyntaxDiagKind::RuneLiteralTooLong,
        super::LexErrorKind::UnterminatedBlockComment => SyntaxDiagKind::UnterminatedBlockComment,
        super::LexErrorKind::UnterminatedTemplateLiteral => {
            SyntaxDiagKind::UnterminatedTemplateLiteral
        }
        super::LexErrorKind::MissingDigitsAfterBasePrefix { .. } => {
            SyntaxDiagKind::MissingDigitsAfterBasePrefix
        }
        super::LexErrorKind::InvalidDigitForBase { .. } => SyntaxDiagKind::InvalidDigitForBase,
        super::LexErrorKind::UnexpectedUnderscoreInNumberLiteral => {
            SyntaxDiagKind::UnexpectedUnderscoreInNumberLiteral
        }
        super::LexErrorKind::MissingDigitAfterUnderscoreInNumberLiteral => {
            SyntaxDiagKind::MissingDigitAfterUnderscoreInNumberLiteral
        }
        super::LexErrorKind::MissingExponentDigits => SyntaxDiagKind::MissingExponentDigits,
        super::LexErrorKind::MissingEscapeCode => SyntaxDiagKind::MissingEscapeCode,
        super::LexErrorKind::UnexpectedEscape { .. } => SyntaxDiagKind::UnexpectedEscape,
        super::LexErrorKind::MissingHexDigitsInByteEscape => {
            SyntaxDiagKind::MissingHexDigitsInByteEscape
        }
        super::LexErrorKind::InvalidHexDigitInByteEscape { .. } => {
            SyntaxDiagKind::InvalidHexDigitInByteEscape
        }
        super::LexErrorKind::MissingHexDigitsInUnicodeEscape => {
            SyntaxDiagKind::MissingHexDigitsInUnicodeEscape
        }
        super::LexErrorKind::InvalidHexDigitInUnicodeEscape { .. } => {
            SyntaxDiagKind::InvalidHexDigitInUnicodeEscape
        }
        super::LexErrorKind::ExpectedFourOrSixHexDigitsInUnicodeEscape => {
            SyntaxDiagKind::ExpectedFourOrSixHexDigitsInUnicodeEscape
        }
        super::LexErrorKind::InvalidUnicodeScalar { .. } => SyntaxDiagKind::InvalidUnicodeScalar,
    }
}

pub const fn parse_error_kind(source: super::ParseErrorKind) -> SyntaxDiagKind {
    match source {
        super::ParseErrorKind::ExpectedToken { .. } => SyntaxDiagKind::ExpectedToken,
        super::ParseErrorKind::ExpectedExpression { .. } => SyntaxDiagKind::ExpectedExpression,
        super::ParseErrorKind::ExpectedPattern { .. } => SyntaxDiagKind::ExpectedPattern,
        super::ParseErrorKind::ExpectedMember { .. } => SyntaxDiagKind::ExpectedMember,
        super::ParseErrorKind::ExpectedIdentifier { .. } => SyntaxDiagKind::ExpectedIdentifier,
        super::ParseErrorKind::ReservedKeywordIdentifier { .. } => {
            SyntaxDiagKind::ReservedKeywordIdentifier
        }
        super::ParseErrorKind::ExpectedSpliceTarget { .. } => SyntaxDiagKind::ExpectedSpliceTarget,
        super::ParseErrorKind::ExpectedOperatorMemberName { .. } => {
            SyntaxDiagKind::ExpectedOperatorMemberName
        }
        super::ParseErrorKind::ExpectedFieldTarget { .. } => SyntaxDiagKind::ExpectedFieldTarget,
        super::ParseErrorKind::ExpectedConstraintOperator { .. } => {
            SyntaxDiagKind::ExpectedConstraintOperator
        }
        super::ParseErrorKind::ExpectedAttrValue { .. } => SyntaxDiagKind::ExpectedAttrValue,
        super::ParseErrorKind::SpliceOutsideQuote => SyntaxDiagKind::SpliceOutsideQuote,
        super::ParseErrorKind::NonAssociativeChain => SyntaxDiagKind::NonAssociativeChain,
    }
}
