// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use music_base::diag::DiagContext;
use super::RuntimeDiagKind;

struct CatalogEntry {
    kind: RuntimeDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    secondary: Option<&'static str>,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: RuntimeDiagKind::RootModuleRequired,
        code: 6000,
        message: "runtime needs root module",
        primary: "runtime needs root module",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: RuntimeDiagKind::MissingModuleSource,
        code: 6001,
        message: "runtime module source `{spec}` missing",
        primary: "runtime module source `{spec}` missing",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: RuntimeDiagKind::InvalidSyntaxValue,
        code: 6002,
        message: "syntax value `{found}` invalid",
        primary: "syntax value `{found}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: RuntimeDiagKind::SessionFailed,
        code: 6003,
        message: "runtime session `{phase}` failed (`{detail}`)",
        primary: "runtime session `{phase}` failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: RuntimeDiagKind::VmExecutionFailed,
        code: 6004,
        message: "VM execution failed (`{source}`)",
        primary: "VM execution failed",
        secondary: None,
        help: None,
    },
];

fn entry(kind: RuntimeDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: RuntimeDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: RuntimeDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: RuntimeDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn render_message(kind: RuntimeDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).message)
}

pub fn render_primary(kind: RuntimeDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).primary)
}

pub fn secondary(kind: RuntimeDiagKind) -> Option<&'static str> {
    entry(kind).secondary
}

pub fn render_secondary(kind: RuntimeDiagKind, context: &DiagContext) -> Option<String> {
    entry(kind).secondary.map(|secondary| context.render(secondary))
}

pub fn help(kind: RuntimeDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<RuntimeDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn runtime_error_kind(source: &crate::RuntimeErrorKind) -> RuntimeDiagKind {
    match source {
        crate::RuntimeErrorKind::RootModuleRequired => RuntimeDiagKind::RootModuleRequired,
        crate::RuntimeErrorKind::MissingModuleSource { .. } => RuntimeDiagKind::MissingModuleSource,
        crate::RuntimeErrorKind::InvalidSyntaxValue { .. } => RuntimeDiagKind::InvalidSyntaxValue,
        crate::RuntimeErrorKind::SessionFailed { .. } => RuntimeDiagKind::SessionFailed,
        crate::RuntimeErrorKind::VmExecutionFailed(_) => RuntimeDiagKind::VmExecutionFailed,
    }
}
