[package]
name = "musi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
musi_fmt = { path = "../musi_fmt" }
clap = { workspace = true }
music_base = { path = "../music_base" }
music_session = { path = "../music_session" }
musi_tooling = { path = "../musi_tooling" }
musi_native = { path = "../musi_native" }
musi_lsp = { path = "../musi_lsp" }
musi_project = { path = "../musi_project" }
musi_rt = { path = "../musi_rt" }
musi_vm = { path = "../musi_vm" }
music_module = { path = "../music_module" }
music_seam = { path = "../music_seam" }
music_sema = { path = "../music_sema" }
serde_json = { workspace = true }

[dev-dependencies]
sha2 = { workspace = true }

[lints]
workspace = true
