// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use super::SessionDiagKind;
use music_base::diag::DiagContext;

struct CatalogEntry {
    kind: SessionDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    secondary: Option<&'static str>,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: SessionDiagKind::ModuleNotRegistered,
        code: 5200,
        message: "module `{key}` not registered",
        primary: "module `{key}` not registered",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::SourceMapUpdateFailed,
        code: 5201,
        message: "source map update failed (`{kind}`)",
        primary: "source map update failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::ModuleParseFailed,
        code: 5202,
        message: "module `{module}` parse failed",
        primary: "module `{module}` parse failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::ModuleResolveFailed,
        code: 5203,
        message: "module `{module}` resolve failed",
        primary: "module `{module}` resolve failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::ModuleSemanticCheckFailed,
        code: 5204,
        message: "module `{module}` semantic check failed",
        primary: "module `{module}` semantic check failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::ModuleLoweringFailed,
        code: 5205,
        message: "module `{module}` lowering failed",
        primary: "module `{module}` lowering failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::ModuleEmissionFailed,
        code: 5206,
        message: "module `{module}` emission failed",
        primary: "module `{module}` emission failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::LawSuiteSynthesisFailed,
        code: 5207,
        message: "module `{module}` law-suite synthesis failed (`{reason}`)",
        primary: "module `{module}` law-suite synthesis failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::ArtifactTransportFailed,
        code: 5208,
        message: "artifact transport failed (`{source}`)",
        primary: "artifact transport failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::SourceRegistryOverflow,
        code: 5209,
        message: "source registry overflow",
        primary: "source registry overflow",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::SourceTooLarge,
        code: 5210,
        message: "source text `{len}` bytes exceeds limit",
        primary: "source text `{len}` bytes exceeds limit",
        secondary: None,
        help: None,
    },
];

fn entry(kind: SessionDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: SessionDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: SessionDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: SessionDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn render_message(kind: SessionDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).message)
}

pub fn render_primary(kind: SessionDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).primary)
}

pub fn secondary(kind: SessionDiagKind) -> Option<&'static str> {
    entry(kind).secondary
}

pub fn render_secondary(kind: SessionDiagKind, context: &DiagContext) -> Option<String> {
    entry(kind)
        .secondary
        .map(|secondary| context.render(secondary))
}

pub fn help(kind: SessionDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<SessionDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn session_error_kind(source: &crate::SessionError) -> SessionDiagKind {
    match source {
        crate::SessionError::ModuleNotRegistered { .. } => SessionDiagKind::ModuleNotRegistered,
        crate::SessionError::SourceMapUpdateFailed { .. } => SessionDiagKind::SourceMapUpdateFailed,
        crate::SessionError::ModuleParseFailed { .. } => SessionDiagKind::ModuleParseFailed,
        crate::SessionError::ModuleResolveFailed { .. } => SessionDiagKind::ModuleResolveFailed,
        crate::SessionError::ModuleSemanticCheckFailed { .. } => {
            SessionDiagKind::ModuleSemanticCheckFailed
        }
        crate::SessionError::ModuleLoweringFailed { .. } => SessionDiagKind::ModuleLoweringFailed,
        crate::SessionError::ModuleEmissionFailed { .. } => SessionDiagKind::ModuleEmissionFailed,
        crate::SessionError::LawSuiteSynthesisFailed { .. } => {
            SessionDiagKind::LawSuiteSynthesisFailed
        }
        crate::SessionError::ArtifactTransportFailed(_) => SessionDiagKind::ArtifactTransportFailed,
    }
}

pub const fn session_source_map_error_kind(
    source: &crate::SessionSourceMapError,
) -> SessionDiagKind {
    match source {
        crate::SessionSourceMapError::SourceRegistryOverflow => {
            SessionDiagKind::SourceRegistryOverflow
        }
        crate::SessionSourceMapError::SourceTooLarge { .. } => SessionDiagKind::SourceTooLarge,
    }
}
