// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use super::CliDiagKind;
use music_base::diag::DiagContext;

struct CatalogEntry {
    kind: CliDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    secondary: Option<&'static str>,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: CliDiagKind::MissingCurrentDirectory,
        code: 5300,
        message: "missing current directory",
        primary: "missing current directory",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: CliDiagKind::TaskFailed,
        code: 5301,
        message: "task `{name}` failed",
        primary: "task `{name}` failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: CliDiagKind::UnsupportedRunArgs,
        code: 5302,
        message: "musi run argument `{argument}` unsupported",
        primary: "musi run argument `{argument}` unsupported",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: CliDiagKind::PackageAlreadyInitialized,
        code: 5303,
        message: "package path `{path}` already initialized",
        primary: "package path `{path}` already initialized",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: CliDiagKind::MissingPackageName,
        code: 5304,
        message: "missing package name for `{path}`",
        primary: "missing package name for `{path}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: CliDiagKind::UnknownTarget,
        code: 5305,
        message: "project target `{target}` unknown",
        primary: "project target `{target}` not found",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: CliDiagKind::CheckCommandFailed,
        code: 5306,
        message: "musi check command failed",
        primary: "musi check command failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: CliDiagKind::CommandUnavailable,
        code: 5307,
        message: "command `{command}` unavailable because `{feature}` not implemented",
        primary: "command `{command}` unavailable",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: CliDiagKind::LspServerFailed,
        code: 5308,
        message: "LSP server failed (`{message}`)",
        primary: "LSP server failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: CliDiagKind::IncompatibleCommandArgs,
        code: 5309,
        message: "incompatible command arguments `{left}` and `{right}`",
        primary: "incompatible command arguments `{left}` and `{right}`",
        secondary: None,
        help: None,
    },
];

fn entry(kind: CliDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: CliDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: CliDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: CliDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn render_message(kind: CliDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).message)
}

pub fn render_primary(kind: CliDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).primary)
}

pub fn secondary(kind: CliDiagKind) -> Option<&'static str> {
    entry(kind).secondary
}

pub fn render_secondary(kind: CliDiagKind, context: &DiagContext) -> Option<String> {
    entry(kind)
        .secondary
        .map(|secondary| context.render(secondary))
}

pub fn help(kind: CliDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<CliDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn cli_error_kind(source: &crate::MusiError) -> Option<CliDiagKind> {
    match source {
        crate::MusiError::ProjectModelFailed(_)
        | crate::MusiError::SessionCompilationFailed(_)
        | crate::MusiError::RuntimeExecutionFailed(_)
        | crate::MusiError::ToolingIoFailed(_)
        | crate::MusiError::FormattingFailed(_)
        | crate::MusiError::JsonSerializationFailed(_) => None,
        crate::MusiError::MissingCurrentDirectory => Some(CliDiagKind::MissingCurrentDirectory),
        crate::MusiError::TaskFailed { .. } => Some(CliDiagKind::TaskFailed),
        crate::MusiError::UnsupportedRunArgs { .. } => Some(CliDiagKind::UnsupportedRunArgs),
        crate::MusiError::PackageAlreadyInitialized { .. } => {
            Some(CliDiagKind::PackageAlreadyInitialized)
        }
        crate::MusiError::MissingPackageName { .. } => Some(CliDiagKind::MissingPackageName),
        crate::MusiError::UnknownTarget { .. } => Some(CliDiagKind::UnknownTarget),
        crate::MusiError::CheckCommandFailed => Some(CliDiagKind::CheckCommandFailed),
        crate::MusiError::CommandUnavailable { .. } => Some(CliDiagKind::CommandUnavailable),
        crate::MusiError::LspServerFailed { .. } => Some(CliDiagKind::LspServerFailed),
        crate::MusiError::IncompatibleCommandArgs { .. } => {
            Some(CliDiagKind::IncompatibleCommandArgs)
        }
    }
}
