// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use music_base::diag::DiagContext;
use super::EmitDiagKind;

struct CatalogEntry {
    kind: EmitDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    secondary: Option<&'static str>,
    help: Option<&'static str>,
}

#[rustfmt::skip]
const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: EmitDiagKind::MissingExportTarget,
        code: 3500,
        message: "export `{export}` missing emit target",
        primary: "export `{export}` missing emit target",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownTypeValue,
        code: 3501,
        message: "emitted type value `{type}` unknown",
        primary: "emitted type value `{type}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownTypeNameForOp,
        code: 3502,
        message: "operation `{operation}` type name `{type}` unknown",
        primary: "operation `{operation}` type name `{type}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnsupportedBinaryOperator,
        code: 3503,
        message: "binary operator `{operator}` unsupported",
        primary: "binary operator `{operator}` unsupported",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::CaseVariantDispatchRequiresSingleDataType,
        code: 3504,
        message: "case variant dispatch needs single data type",
        primary: "case variant dispatch needs single data type",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownDataType,
        code: 3505,
        message: "emitted data type `{type}` unknown",
        primary: "emitted data type `{type}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::SpreadCallArgsNotEmitted,
        code: 3506,
        message: "spread call arguments have no emitted form",
        primary: "spread call arguments have no emitted form",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownClosureTarget,
        code: 3507,
        message: "emitted closure target `{target}` unknown",
        primary: "emitted closure target `{target}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownEffect,
        code: 3508,
        message: "emitted effect `{effect}` unknown",
        primary: "emitted effect `{effect}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownHandlerType,
        code: 3509,
        message: "emitted answer type `{type}` unknown",
        primary: "emitted answer type `{type}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownRecordType,
        code: 3510,
        message: "emitted record type `{type}` unknown",
        primary: "emitted record type `{type}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::RecordLiteralMissingFieldValue,
        code: 3511,
        message: "record literal field `{field}` missing value",
        primary: "record literal field `{field}` missing value",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::RecordUpdateMissingFieldValue,
        code: 3512,
        message: "record update field `{field}` missing value",
        primary: "record update field `{field}` missing value",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownSequenceType,
        code: 3513,
        message: "emitted sequence type `{type}` unknown",
        primary: "emitted sequence type `{type}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::InvalidSyntaxLiteral,
        code: 3514,
        message: "syntax literal `{literal}` invalid",
        primary: "syntax literal `{literal}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::InvalidIntegerLiteral,
        code: 3515,
        message: "integer literal `{literal}` invalid",
        primary: "integer literal `{literal}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::InvalidFloatLiteral,
        code: 3516,
        message: "float literal `{literal}` invalid",
        primary: "float literal `{literal}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnsupportedNameRef,
        code: 3517,
        message: "name reference `{name}` unsupported",
        primary: "name reference `{name}` unsupported",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnsupportedAssignTarget,
        code: 3518,
        message: "emitted assignment target `{target}` unsupported",
        primary: "emitted assignment target `{target}` unsupported",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::EmitInvariantViolated,
        code: 3519,
        message: "emit invariant violated",
        primary: "{detail}",
        secondary: None,
        help: None,
    },
];

fn entry(kind: EmitDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: EmitDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: EmitDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: EmitDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn render_message(kind: EmitDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).message)
}

pub fn render_primary(kind: EmitDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).primary)
}

pub fn secondary(kind: EmitDiagKind) -> Option<&'static str> {
    entry(kind).secondary
}

pub fn render_secondary(kind: EmitDiagKind, context: &DiagContext) -> Option<String> {
    entry(kind).secondary.map(|secondary| context.render(secondary))
}

pub fn help(kind: EmitDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<EmitDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}
