use crate::instruction::OperandShape;

use super::super::{Opcode, OpcodeFamily};
use super::info::{OpcodeInfo, opcode_info};

pub(super) const OPCODES: &[OpcodeInfo] = &[
    opcode_info(
        Opcode::Add,
        OpcodeFamily::Scalar,
        "add",
        OperandShape::None,
        0x21,
    ),
    opcode_info(
        Opcode::Sub,
        OpcodeFamily::Scalar,
        "sub",
        OperandShape::None,
        0x22,
    ),
    opcode_info(
        Opcode::Mul,
        OpcodeFamily::Scalar,
        "mul",
        OperandShape::None,
        0x23,
    ),
    opcode_info(
        Opcode::DivS,
        OpcodeFamily::Scalar,
        "div.s",
        OperandShape::None,
        0x27,
    ),
    opcode_info(
        Opcode::RemS,
        OpcodeFamily::Scalar,
        "rem.s",
        OperandShape::None,
        0x29,
    ),
    opcode_info(
        Opcode::And,
        OpcodeFamily::Scalar,
        "and",
        OperandShape::None,
        0x2B,
    ),
    opcode_info(
        Opcode::Or,
        OpcodeFamily::Scalar,
        "or",
        OperandShape::None,
        0x2C,
    ),
    opcode_info(
        Opcode::Xor,
        OpcodeFamily::Scalar,
        "xor",
        OperandShape::None,
        0x2D,
    ),
    opcode_info(
        Opcode::Not,
        OpcodeFamily::Scalar,
        "not",
        OperandShape::None,
        0x2E,
    ),
    opcode_info(
        Opcode::Ceq,
        OpcodeFamily::Scalar,
        "cmp.eq",
        OperandShape::None,
        0x37,
    ),
    opcode_info(
        Opcode::Cne,
        OpcodeFamily::Scalar,
        "cmp.ne",
        OperandShape::None,
        0x38,
    ),
    opcode_info(
        Opcode::CltS,
        OpcodeFamily::Scalar,
        "cmp.lt",
        OperandShape::None,
        0x39,
    ),
    opcode_info(
        Opcode::CgtS,
        OpcodeFamily::Scalar,
        "cmp.gt",
        OperandShape::None,
        0x3B,
    ),
    opcode_info(
        Opcode::CleS,
        OpcodeFamily::Scalar,
        "cmp.le",
        OperandShape::None,
        0x3D,
    ),
    opcode_info(
        Opcode::CgeS,
        OpcodeFamily::Scalar,
        "cmp.ge",
        OperandShape::None,
        0x40,
    ),
];
