use crate::{Interner, Symbol};
use music_builtin::BuiltinTypeId;

#[derive(Debug, Clone, Copy)]
pub struct KnownSymbols {
    pub type_: Symbol,
    pub array: Symbol,
    pub any: Symbol,
    pub unknown: Symbol,
    pub syntax: Symbol,
    pub empty: Symbol,
    pub unit: Symbol,
    pub bool_: Symbol,
    pub nat: Symbol,
    pub int_: Symbol,
    pub int8: Symbol,
    pub int16: Symbol,
    pub int32: Symbol,
    pub int64: Symbol,
    pub nat8: Symbol,
    pub nat16: Symbol,
    pub nat32: Symbol,
    pub nat64: Symbol,
    pub float_: Symbol,
    pub float32: Symbol,
    pub float64: Symbol,
    pub string_: Symbol,
    pub rune: Symbol,
    pub bits: Symbol,
    pub word: Symbol,
    pub word8: Symbol,
    pub word16: Symbol,
    pub word32: Symbol,
    pub word64: Symbol,
    pub range: Symbol,
    pub pin: Symbol,
    pub closed_range: Symbol,
    pub partial_range_from: Symbol,
    pub partial_range_up_to: Symbol,
    pub partial_range_thru: Symbol,
    pub handler: Symbol,
    pub rangeable: Symbol,
    pub range_bounds: Symbol,
    pub compare: Symbol,
    pub next: Symbol,
    pub prev: Symbol,
    pub default_lower_bound: Symbol,
    pub default_upper_bound: Symbol,
    pub cstring: Symbol,
    pub cptr: Symbol,
    pub abort: Symbol,
    pub abort_op: Symbol,
    pub known: Symbol,
    pub intrinsic: Symbol,
    pub name_key: Symbol,
    pub symbol_key: Symbol,
    pub message_key: Symbol,
    pub replace_key: Symbol,
    pub version_key: Symbol,
    pub lang_option: Symbol,
    pub some: Symbol,
    pub none: Symbol,
}

impl KnownSymbols {
    #[must_use]
    pub fn new(interner: &mut Interner) -> Self {
        Self {
            type_: interner.intern(BuiltinTypeId::Type.name()),
            array: interner.intern(BuiltinTypeId::Array.name()),
            any: interner.intern(BuiltinTypeId::Any.name()),
            unknown: interner.intern(BuiltinTypeId::Unknown.name()),
            syntax: interner.intern(BuiltinTypeId::Syntax.name()),
            empty: interner.intern(BuiltinTypeId::Empty.name()),
            unit: interner.intern(BuiltinTypeId::Unit.name()),
            bool_: interner.intern(BuiltinTypeId::Bool.name()),
            nat: interner.intern(BuiltinTypeId::Nat.name()),
            int_: interner.intern(BuiltinTypeId::Int.name()),
            int8: interner.intern(BuiltinTypeId::Int8.name()),
            int16: interner.intern(BuiltinTypeId::Int16.name()),
            int32: interner.intern(BuiltinTypeId::Int32.name()),
            int64: interner.intern(BuiltinTypeId::Int64.name()),
            nat8: interner.intern(BuiltinTypeId::Nat8.name()),
            nat16: interner.intern(BuiltinTypeId::Nat16.name()),
            nat32: interner.intern(BuiltinTypeId::Nat32.name()),
            nat64: interner.intern(BuiltinTypeId::Nat64.name()),
            float_: interner.intern(BuiltinTypeId::Float.name()),
            float32: interner.intern(BuiltinTypeId::Float32.name()),
            float64: interner.intern(BuiltinTypeId::Float64.name()),
            string_: interner.intern(BuiltinTypeId::String.name()),
            rune: interner.intern(BuiltinTypeId::Rune.name()),
            bits: interner.intern(BuiltinTypeId::Bits.name()),
            word: interner.intern(BuiltinTypeId::Word.name()),
            word8: interner.intern(BuiltinTypeId::Word8.name()),
            word16: interner.intern(BuiltinTypeId::Word16.name()),
            word32: interner.intern(BuiltinTypeId::Word32.name()),
            word64: interner.intern(BuiltinTypeId::Word64.name()),
            range: interner.intern(BuiltinTypeId::Range.name()),
            pin: interner.intern(BuiltinTypeId::Pin.name()),
            closed_range: interner.intern(BuiltinTypeId::ClosedRange.name()),
            partial_range_from: interner.intern(BuiltinTypeId::PartialRangeFrom.name()),
            partial_range_up_to: interner.intern(BuiltinTypeId::PartialRangeUpTo.name()),
            partial_range_thru: interner.intern(BuiltinTypeId::PartialRangeThru.name()),
            handler: interner.intern("Handler"),
            rangeable: interner.intern("Rangeable"),
            range_bounds: interner.intern("RangeBounds"),
            compare: interner.intern("compare"),
            next: interner.intern("next"),
            prev: interner.intern("prev"),
            default_lower_bound: interner.intern("defaultLowerBound"),
            default_upper_bound: interner.intern("defaultUpperBound"),
            cstring: interner.intern(BuiltinTypeId::CString.name()),
            cptr: interner.intern(BuiltinTypeId::CPtr.name()),
            abort: interner.intern("Abort"),
            abort_op: interner.intern("abort"),
            known: interner.intern("known"),
            intrinsic: interner.intern("intrinsic"),
            name_key: interner.intern("name"),
            symbol_key: interner.intern("symbol"),
            message_key: interner.intern("message"),
            replace_key: interner.intern("replace"),
            version_key: interner.intern("version"),
            lang_option: interner.intern("Option"),
            some: interner.intern("Some"),
            none: interner.intern("None"),
        }
    }

    #[must_use]
    pub const fn compiler_prelude(self) -> [Symbol; 40] {
        [
            self.type_,
            self.array,
            self.any,
            self.unknown,
            self.syntax,
            self.empty,
            self.unit,
            self.bool_,
            self.nat,
            self.int_,
            self.int8,
            self.int16,
            self.int32,
            self.int64,
            self.nat8,
            self.nat16,
            self.nat32,
            self.nat64,
            self.float_,
            self.float32,
            self.float64,
            self.string_,
            self.rune,
            self.bits,
            self.word,
            self.word8,
            self.word16,
            self.word32,
            self.word64,
            self.range,
            self.pin,
            self.closed_range,
            self.partial_range_from,
            self.partial_range_up_to,
            self.partial_range_thru,
            self.rangeable,
            self.range_bounds,
            self.cstring,
            self.cptr,
            self.abort,
        ]
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests;
