// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use music_base::diag::DiagContext;
use super::ResolveDiagKind;

struct CatalogEntry {
    kind: ResolveDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    secondary: Option<&'static str>,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: ResolveDiagKind::ExpectedName,
        code: 3200,
        message: "`let` binding needs name",
        primary: "`let` binding name belongs here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ResolveDiagKind::InvalidStmt,
        code: 3201,
        message: "top-level statement invalid",
        primary: "top-level item or expression belongs here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ResolveDiagKind::UnboundName,
        code: 3202,
        message: "unbound name `{name}`",
        primary: "name `{name}` unresolved in this scope",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ResolveDiagKind::ImportResolveFailed,
        code: 3203,
        message: "source import specifier `{spec}` unresolved",
        primary: "{reason} `{spec}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ResolveDiagKind::InvalidImportSpec,
        code: 3204,
        message: "import specifier invalid",
        primary: "string literal import specifier belongs here",
        secondary: None,
        help: None,
    },
];

fn entry(kind: ResolveDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: ResolveDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: ResolveDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: ResolveDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn render_message(kind: ResolveDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).message)
}

pub fn render_primary(kind: ResolveDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).primary)
}

pub fn secondary(kind: ResolveDiagKind) -> Option<&'static str> {
    entry(kind).secondary
}

pub fn render_secondary(kind: ResolveDiagKind, context: &DiagContext) -> Option<String> {
    entry(kind).secondary.map(|secondary| context.render(secondary))
}

pub fn help(kind: ResolveDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<ResolveDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}
