// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use music_base::diag::DiagContext;
use super::IrDiagKind;

struct CatalogEntry {
    kind: IrDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    secondary: Option<&'static str>,
    help: Option<&'static str>,
}

#[rustfmt::skip]
const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: IrDiagKind::InvalidSurfaceTypeId,
        code: 3400,
        message: "surface type identifier `{id}` invalid",
        primary: "surface type identifier `{id}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: IrDiagKind::LoweringRequiresSemaCleanModule,
        code: 3401,
        message: "IR lowering needs semantic-clean module",
        primary: "IR lowering needs semantic-clean module",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: IrDiagKind::LoweringInvariantViolated,
        code: 3402,
        message: "IR lowering invariant `{subject}` violated",
        primary: "IR lowering invariant `{subject}` violated",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: IrDiagKind::LoweringInputMissing,
        code: 3403,
        message: "IR lowering input `{input}` missing",
        primary: "lowering input `{input}` missing",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: IrDiagKind::LoweringStateInvalid,
        code: 3404,
        message: "IR lowering state `{state}` invalid",
        primary: "lowering state `{state}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: IrDiagKind::LoweringTargetUnsupported,
        code: 3405,
        message: "IR lowering target `{target}` unsupported",
        primary: "lowering target `{target}` unsupported",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: IrDiagKind::LoweringSymbolUnknown,
        code: 3406,
        message: "IR lowering symbol `{symbol}` unknown",
        primary: "lowering symbol `{symbol}` unknown",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: IrDiagKind::LoweringOverflow,
        code: 3407,
        message: "IR lowering `{subject}` exceeds `{limit}`",
        primary: "lowering `{subject}` too large",
        secondary: None,
        help: None,
    },
];

fn entry(kind: IrDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: IrDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: IrDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: IrDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn render_message(kind: IrDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).message)
}

pub fn render_primary(kind: IrDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).primary)
}

pub fn secondary(kind: IrDiagKind) -> Option<&'static str> {
    entry(kind).secondary
}

pub fn render_secondary(kind: IrDiagKind, context: &DiagContext) -> Option<String> {
    entry(kind).secondary.map(|secondary| context.render(secondary))
}

pub fn help(kind: IrDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<IrDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}
