// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use music_base::diag::DiagContext;
use super::VmDiagKind;

struct CatalogEntry {
    kind: VmDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    secondary: Option<&'static str>,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: VmDiagKind::SeamDecodeFailed,
        code: 6100,
        message: "SEAM decode failed (`{detail}`)",
        primary: "SEAM decode failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidProgramShape,
        code: 6101,
        message: "program shape invalid (`{detail}`)",
        primary: "program shape invalid (`{detail}`)",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidTypeTerm,
        code: 6102,
        message: "type term `{ty}` invalid (`{detail}`)",
        primary: "type term `{ty}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidSyntaxConstant,
        code: 6103,
        message: "syntax constant invalid (`{detail}`)",
        primary: "syntax constant invalid (`{detail}`)",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::VmInitializationRequired,
        code: 6104,
        message: "VM needs initialization",
        primary: "VM needs initialization",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::ModuleInitCycle,
        code: 6105,
        message: "module `{spec}` initialization cycle detected",
        primary: "module `{spec}` initialization cycle detected",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::ExportNotFound,
        code: 6106,
        message: "module `{module}` missing export `{export}`",
        primary: "export `{export}` missing",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::OpaqueExport,
        code: 6107,
        message: "opaque export `{export}` inaccessible from `{module}`",
        primary: "opaque export `{export}` inaccessible",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::NonCallableValue,
        code: 6108,
        message: "call target expected callable value, found `{found}`",
        primary: "call target expected callable value, found `{found}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::MissingEntryProcedure,
        code: 6109,
        message: "module `{module}` missing entry procedure",
        primary: "module `{module}` missing entry procedure",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::StackEmpty,
        code: 6110,
        message: "{stack} stack empty",
        primary: "{stack} stack empty",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::OperandCountMismatch,
        code: 6111,
        message: "operand stack expected `{needed}` values, found `{available}`",
        primary: "operand stack has `{available}` values",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::IndexOutOfBounds,
        code: 6112,
        message: "{space} `{index}` out of bounds for `{owner}` with `{len}` entries",
        primary: "{space} `{index}` out of bounds",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidBranchTarget,
        code: 6113,
        message: "procedure `{procedure}` branch target `{target}` invalid",
        primary: "branch target `{target}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidOperandForOpcode,
        code: 6114,
        message: "opcode `{opcode}` operand shape `{found}` invalid",
        primary: "operand shape `{found}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidValueKind,
        code: 6115,
        message: "value kind expected `{expected}`, found `{found}`",
        primary: "value kind `{found}` found",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidSequenceIndex,
        code: 6116,
        message: "sequence index `{index}` invalid for length `{len}`",
        primary: "sequence index `{index}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::EmptySequenceIndexList,
        code: 6117,
        message: "sequence index list `[]` empty",
        primary: "sequence index list `[]` empty",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidRangeBounds,
        code: 6118,
        message: "range bounds `{start}` and `{end}` invalid",
        primary: "range bounds `{start}` and `{end}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidRangeEvidence,
        code: 6119,
        message: "range answer invalid for value kind `{found}`",
        primary: "range answer invalid for value kind `{found}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidRangeStep,
        code: 6120,
        message: "range step invalid (`{detail}`)",
        primary: "range step invalid (`{detail}`)",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::RangeMaterializeTooLarge,
        code: 6121,
        message: "range materialize length `{len}` exceeds limit `{limit}`",
        primary: "range materialize length `{len}` too large",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidDataIndex,
        code: 6122,
        message: "data field index `{index}` invalid for length `{len}`",
        primary: "data field index `{index}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidTypeCast,
        code: 6123,
        message: "type cast target expected `{expected}`, found `{found}`",
        primary: "type cast found `{found}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::ArithmeticFailed,
        code: 6124,
        message: "arithmetic failed (`{detail}`)",
        primary: "arithmetic failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::ModuleLoadRejected,
        code: 6125,
        message: "module `{spec}` load rejected",
        primary: "module `{spec}` load rejected",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::ForeignCallRejected,
        code: 6126,
        message: "native call `{native}` rejected",
        primary: "native call `{native}` rejected",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::PointerIntrinsicFailed,
        code: 6127,
        message: "pointer intrinsic `{intrinsic}` failed (`{detail}`)",
        primary: "pointer intrinsic `{intrinsic}` failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::NativeCallFailed,
        code: 6128,
        message: "native call `{native}` failed during `{stage}` for `{subject}` (`{detail}`)",
        primary: "native call `{native}` failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::EffectRejected,
        code: 6129,
        message: "effect `{effect}` operation `{op}` rejected (`{reason}`)",
        primary: "effect `{effect}` rejected",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::RootModuleRequired,
        code: 6130,
        message: "VM root module required",
        primary: "VM root module required",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::MissingModuleSource,
        code: 6131,
        message: "VM module source `{spec}` missing",
        primary: "VM module source `{spec}` missing",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::CallArityMismatch,
        code: 6132,
        message: "runtime call `{callee}` expected `{expected}` arguments, found `{found}`",
        primary: "call `{callee}` has `{found}` arguments here",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::HandlerFrameMissing,
        code: 6133,
        message: "answer `{handler_id}` frame depth `{frame_depth}` missing",
        primary: "answer `{handler_id}` frame missing",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::MissingMatchingHandlerPop,
        code: 6134,
        message: "procedure `{procedure}` missing matching `hdl.pop`",
        primary: "matching `hdl.pop` missing",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::HeapLimitExceeded,
        code: 6135,
        message: "heap limit `{limit}` exceeded with `{allocated}` allocated bytes",
        primary: "heap limit `{limit}` exceeded",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::HeapObjectTooLarge,
        code: 6136,
        message: "heap object size `{bytes}` exceeds limit `{limit}`",
        primary: "heap object size `{bytes}` too large",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::StackFrameLimitExceeded,
        code: 6137,
        message: "stack frame limit `{limit}` exceeded with `{frames}` frames",
        primary: "stack frame limit `{limit}` exceeded",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InstructionBudgetExhausted,
        code: 6138,
        message: "instruction budget `{budget}` exhausted",
        primary: "instruction budget `{budget}` exhausted",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::RuntimeEffectArgsInvalid,
        code: 6139,
        message: "runtime effect `{effect}.{op}` expected `{expected}`, found `{found}`",
        primary: "runtime effect `{op}` arguments invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::RuntimeEffectOperationFailed,
        code: 6140,
        message: "runtime effect `{effect}` operation `{op}` failed (`{source}`)",
        primary: "runtime effect `{op}` failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::RuntimeHostUnavailable,
        code: 6141,
        message: "runtime host `{subject}` unavailable",
        primary: "runtime host `{subject}` unavailable",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::RuntimeEffectUnsupported,
        code: 6149,
        message: "runtime effect `{effect}.{op}` unsupported",
        primary: "runtime effect operation `{op}` unsupported",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::NativeArgumentTypeMismatch,
        code: 6142,
        message: "native argument `{index}` expected `{expected}`, found `{found}`",
        primary: "native argument `{index}` type mismatch",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::NativeArgumentOutOfRange,
        code: 6143,
        message: "native argument `{index}` out of range for `{expected}`",
        primary: "native argument `{index}` out of range",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::NativeArgumentInvalid,
        code: 6150,
        message: "native argument `{index}` `{subject}` invalid",
        primary: "native argument `{index}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::NativeLayoutMissing,
        code: 6144,
        message: "native ABI layout for `{ty}` missing",
        primary: "native ABI layout `{ty}` missing",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::NativeFieldMissing,
        code: 6145,
        message: "native `{subject}` field `{field}` missing",
        primary: "native field `{field}` missing",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::NativeCStringInvalid,
        code: 6146,
        message: "native CString `{subject}` invalid (`{source}`)",
        primary: "native CString `{subject}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::NativeFfiPrepFailed,
        code: 6147,
        message: "native `ffi_prep_cif` failed with status `{status}` for ABI `{abi}`",
        primary: "native `ffi_prep_cif` status `{status}` failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::NativeAbiUnsupported,
        code: 6151,
        message: "native ABI `{subject}` unsupported",
        primary: "native ABI `{subject}` unsupported",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::NativeResultInvalid,
        code: 6152,
        message: "native result `{subject}` invalid",
        primary: "native result `{subject}` invalid",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::PointerArgumentInvalid,
        code: 6148,
        message: "pointer intrinsic argument `{index}` expected `{expected}`, found `{found}`",
        primary: "pointer argument `{index}` invalid",
        secondary: None,
        help: None,
    },
];

fn entry(kind: VmDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: VmDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: VmDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: VmDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn render_message(kind: VmDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).message)
}

pub fn render_primary(kind: VmDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).primary)
}

pub fn secondary(kind: VmDiagKind) -> Option<&'static str> {
    entry(kind).secondary
}

pub fn render_secondary(kind: VmDiagKind, context: &DiagContext) -> Option<String> {
    entry(kind).secondary.map(|secondary| context.render(secondary))
}

pub fn help(kind: VmDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<VmDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn vm_error_kind(source: &crate::VmErrorKind) -> VmDiagKind {
    match source {
        crate::VmErrorKind::SeamDecodeFailed { .. } => VmDiagKind::SeamDecodeFailed,
        crate::VmErrorKind::InvalidProgramShape { .. } => VmDiagKind::InvalidProgramShape,
        crate::VmErrorKind::InvalidTypeTerm { .. } => VmDiagKind::InvalidTypeTerm,
        crate::VmErrorKind::InvalidSyntaxConstant { .. } => VmDiagKind::InvalidSyntaxConstant,
        crate::VmErrorKind::VmInitializationRequired => VmDiagKind::VmInitializationRequired,
        crate::VmErrorKind::ModuleInitCycle { .. } => VmDiagKind::ModuleInitCycle,
        crate::VmErrorKind::ExportNotFound { .. } => VmDiagKind::ExportNotFound,
        crate::VmErrorKind::OpaqueExport { .. } => VmDiagKind::OpaqueExport,
        crate::VmErrorKind::NonCallableValue { .. } => VmDiagKind::NonCallableValue,
        crate::VmErrorKind::MissingEntryProcedure { .. } => VmDiagKind::MissingEntryProcedure,
        crate::VmErrorKind::StackEmpty { .. } => VmDiagKind::StackEmpty,
        crate::VmErrorKind::OperandCountMismatch { .. } => VmDiagKind::OperandCountMismatch,
        crate::VmErrorKind::IndexOutOfBounds { .. } => VmDiagKind::IndexOutOfBounds,
        crate::VmErrorKind::InvalidBranchTarget { .. } => VmDiagKind::InvalidBranchTarget,
        crate::VmErrorKind::InvalidOperandForOpcode { .. } => VmDiagKind::InvalidOperandForOpcode,
        crate::VmErrorKind::InvalidValueKind { .. } => VmDiagKind::InvalidValueKind,
        crate::VmErrorKind::InvalidSequenceIndex { .. } => VmDiagKind::InvalidSequenceIndex,
        crate::VmErrorKind::EmptySequenceIndexList => VmDiagKind::EmptySequenceIndexList,
        crate::VmErrorKind::InvalidRangeBounds { .. } => VmDiagKind::InvalidRangeBounds,
        crate::VmErrorKind::InvalidRangeEvidence { .. } => VmDiagKind::InvalidRangeEvidence,
        crate::VmErrorKind::InvalidRangeStep { .. } => VmDiagKind::InvalidRangeStep,
        crate::VmErrorKind::RangeMaterializeTooLarge { .. } => VmDiagKind::RangeMaterializeTooLarge,
        crate::VmErrorKind::InvalidDataIndex { .. } => VmDiagKind::InvalidDataIndex,
        crate::VmErrorKind::InvalidTypeCast { .. } => VmDiagKind::InvalidTypeCast,
        crate::VmErrorKind::ArithmeticFailed { .. } => VmDiagKind::ArithmeticFailed,
        crate::VmErrorKind::ModuleLoadRejected { .. } => VmDiagKind::ModuleLoadRejected,
        crate::VmErrorKind::ForeignCallRejected { .. } => VmDiagKind::ForeignCallRejected,
        crate::VmErrorKind::PointerIntrinsicFailed { .. } => VmDiagKind::PointerIntrinsicFailed,
        crate::VmErrorKind::NativeCallFailed { .. } => VmDiagKind::NativeCallFailed,
        crate::VmErrorKind::EffectRejected { .. } => VmDiagKind::EffectRejected,
        crate::VmErrorKind::RootModuleRequired => VmDiagKind::RootModuleRequired,
        crate::VmErrorKind::MissingModuleSource { .. } => VmDiagKind::MissingModuleSource,
        crate::VmErrorKind::CallArityMismatch { .. } => VmDiagKind::CallArityMismatch,
        crate::VmErrorKind::HandlerFrameMissing { .. } => VmDiagKind::HandlerFrameMissing,
        crate::VmErrorKind::MissingMatchingHandlerPop { .. } => {
            VmDiagKind::MissingMatchingHandlerPop
        }
        crate::VmErrorKind::HeapLimitExceeded { .. } => VmDiagKind::HeapLimitExceeded,
        crate::VmErrorKind::HeapObjectTooLarge { .. } => VmDiagKind::HeapObjectTooLarge,
        crate::VmErrorKind::StackFrameLimitExceeded { .. } => VmDiagKind::StackFrameLimitExceeded,
        crate::VmErrorKind::InstructionBudgetExhausted { .. } => {
            VmDiagKind::InstructionBudgetExhausted
        }
    }
}
