// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use music_base::diag::DiagContext;
use super::ToolingDiagKind;

struct CatalogEntry {
    kind: ToolingDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    secondary: Option<&'static str>,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: ToolingDiagKind::MissingEntrySource,
        code: 5100,
        message: "missing entry source `{path}`",
        primary: "missing entry source `{path}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ToolingDiagKind::PackageImportRequiresMusi,
        code: 5101,
        message: "import specifier `{spec}` needs `musi` package context",
        primary: "import specifier `{spec}` needs package context",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ToolingDiagKind::MissingImport,
        code: 5102,
        message: "missing import specifier `{spec}` from `{path}`",
        primary: "missing import specifier `{spec}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ToolingDiagKind::ToolingIoFailed,
        code: 5103,
        message: "tooling path `{path}` I/O failed (`{source}`)",
        primary: "tooling path `{path}` I/O failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ToolingDiagKind::SessionCompilationFailed,
        code: 5104,
        message: "tooling session compilation failed (`{source}`)",
        primary: "tooling session compilation failed",
        secondary: None,
        help: None,
    },
];

fn entry(kind: ToolingDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: ToolingDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: ToolingDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: ToolingDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn render_message(kind: ToolingDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).message)
}

pub fn render_primary(kind: ToolingDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).primary)
}

pub fn secondary(kind: ToolingDiagKind) -> Option<&'static str> {
    entry(kind).secondary
}

pub fn render_secondary(kind: ToolingDiagKind, context: &DiagContext) -> Option<String> {
    entry(kind).secondary.map(|secondary| context.render(secondary))
}

pub fn help(kind: ToolingDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<ToolingDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn tooling_error_kind(source: &crate::ToolingError) -> ToolingDiagKind {
    match source {
        crate::ToolingError::MissingEntrySource { .. } => ToolingDiagKind::MissingEntrySource,
        crate::ToolingError::PackageImportRequiresMusi { .. } => {
            ToolingDiagKind::PackageImportRequiresMusi
        }
        crate::ToolingError::MissingImport { .. } => ToolingDiagKind::MissingImport,
        crate::ToolingError::ToolingIoFailed { .. } => ToolingDiagKind::ToolingIoFailed,
        crate::ToolingError::SessionCompilationFailed(_) => {
            ToolingDiagKind::SessionCompilationFailed
        }
    }
}
